################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/dhcp6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ethip6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/icmp6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/inet6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6_addr.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6_frag.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/mld6.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/nd6.c 

OBJS += \
./Middlewares/Lwip/src/core/ipv6/dhcp6.o \
./Middlewares/Lwip/src/core/ipv6/ethip6.o \
./Middlewares/Lwip/src/core/ipv6/icmp6.o \
./Middlewares/Lwip/src/core/ipv6/inet6.o \
./Middlewares/Lwip/src/core/ipv6/ip6.o \
./Middlewares/Lwip/src/core/ipv6/ip6_addr.o \
./Middlewares/Lwip/src/core/ipv6/ip6_frag.o \
./Middlewares/Lwip/src/core/ipv6/mld6.o \
./Middlewares/Lwip/src/core/ipv6/nd6.o 

C_DEPS += \
./Middlewares/Lwip/src/core/ipv6/dhcp6.d \
./Middlewares/Lwip/src/core/ipv6/ethip6.d \
./Middlewares/Lwip/src/core/ipv6/icmp6.d \
./Middlewares/Lwip/src/core/ipv6/inet6.d \
./Middlewares/Lwip/src/core/ipv6/ip6.d \
./Middlewares/Lwip/src/core/ipv6/ip6_addr.d \
./Middlewares/Lwip/src/core/ipv6/ip6_frag.d \
./Middlewares/Lwip/src/core/ipv6/mld6.d \
./Middlewares/Lwip/src/core/ipv6/nd6.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/Lwip/src/core/ipv6/dhcp6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/dhcp6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/ethip6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ethip6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/icmp6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/icmp6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/inet6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/inet6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/ip6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/ip6_addr.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6_addr.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/ip6_frag.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/ip6_frag.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/mld6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/mld6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv6/nd6.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv6/nd6.c Middlewares/Lwip/src/core/ipv6/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv6

clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv6:
	-$(RM) ./Middlewares/Lwip/src/core/ipv6/dhcp6.cyclo ./Middlewares/Lwip/src/core/ipv6/dhcp6.d ./Middlewares/Lwip/src/core/ipv6/dhcp6.o ./Middlewares/Lwip/src/core/ipv6/dhcp6.su ./Middlewares/Lwip/src/core/ipv6/ethip6.cyclo ./Middlewares/Lwip/src/core/ipv6/ethip6.d ./Middlewares/Lwip/src/core/ipv6/ethip6.o ./Middlewares/Lwip/src/core/ipv6/ethip6.su ./Middlewares/Lwip/src/core/ipv6/icmp6.cyclo ./Middlewares/Lwip/src/core/ipv6/icmp6.d ./Middlewares/Lwip/src/core/ipv6/icmp6.o ./Middlewares/Lwip/src/core/ipv6/icmp6.su ./Middlewares/Lwip/src/core/ipv6/inet6.cyclo ./Middlewares/Lwip/src/core/ipv6/inet6.d ./Middlewares/Lwip/src/core/ipv6/inet6.o ./Middlewares/Lwip/src/core/ipv6/inet6.su ./Middlewares/Lwip/src/core/ipv6/ip6.cyclo ./Middlewares/Lwip/src/core/ipv6/ip6.d ./Middlewares/Lwip/src/core/ipv6/ip6.o ./Middlewares/Lwip/src/core/ipv6/ip6.su ./Middlewares/Lwip/src/core/ipv6/ip6_addr.cyclo ./Middlewares/Lwip/src/core/ipv6/ip6_addr.d ./Middlewares/Lwip/src/core/ipv6/ip6_addr.o ./Middlewares/Lwip/src/core/ipv6/ip6_addr.su ./Middlewares/Lwip/src/core/ipv6/ip6_frag.cyclo ./Middlewares/Lwip/src/core/ipv6/ip6_frag.d ./Middlewares/Lwip/src/core/ipv6/ip6_frag.o ./Middlewares/Lwip/src/core/ipv6/ip6_frag.su ./Middlewares/Lwip/src/core/ipv6/mld6.cyclo ./Middlewares/Lwip/src/core/ipv6/mld6.d ./Middlewares/Lwip/src/core/ipv6/mld6.o ./Middlewares/Lwip/src/core/ipv6/mld6.su ./Middlewares/Lwip/src/core/ipv6/nd6.cyclo ./Middlewares/Lwip/src/core/ipv6/nd6.d ./Middlewares/Lwip/src/core/ipv6/nd6.o ./Middlewares/Lwip/src/core/ipv6/nd6.su

.PHONY: clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv6

