################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/api_lib.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/api_msg.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/err.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/if_api.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netbuf.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netdb.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netifapi.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/sockets.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/tcpip.c 

OBJS += \
./Middlewares/Lwip/src/api/api_lib.o \
./Middlewares/Lwip/src/api/api_msg.o \
./Middlewares/Lwip/src/api/err.o \
./Middlewares/Lwip/src/api/if_api.o \
./Middlewares/Lwip/src/api/netbuf.o \
./Middlewares/Lwip/src/api/netdb.o \
./Middlewares/Lwip/src/api/netifapi.o \
./Middlewares/Lwip/src/api/sockets.o \
./Middlewares/Lwip/src/api/tcpip.o 

C_DEPS += \
./Middlewares/Lwip/src/api/api_lib.d \
./Middlewares/Lwip/src/api/api_msg.d \
./Middlewares/Lwip/src/api/err.d \
./Middlewares/Lwip/src/api/if_api.d \
./Middlewares/Lwip/src/api/netbuf.d \
./Middlewares/Lwip/src/api/netdb.d \
./Middlewares/Lwip/src/api/netifapi.d \
./Middlewares/Lwip/src/api/sockets.d \
./Middlewares/Lwip/src/api/tcpip.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/Lwip/src/api/api_lib.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/api_lib.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/api_msg.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/api_msg.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/err.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/err.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/if_api.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/if_api.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/netbuf.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netbuf.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/netdb.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netdb.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/netifapi.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/netifapi.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/sockets.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/sockets.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/api/tcpip.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/api/tcpip.c Middlewares/Lwip/src/api/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-Lwip-2f-src-2f-api

clean-Middlewares-2f-Lwip-2f-src-2f-api:
	-$(RM) ./Middlewares/Lwip/src/api/api_lib.cyclo ./Middlewares/Lwip/src/api/api_lib.d ./Middlewares/Lwip/src/api/api_lib.o ./Middlewares/Lwip/src/api/api_lib.su ./Middlewares/Lwip/src/api/api_msg.cyclo ./Middlewares/Lwip/src/api/api_msg.d ./Middlewares/Lwip/src/api/api_msg.o ./Middlewares/Lwip/src/api/api_msg.su ./Middlewares/Lwip/src/api/err.cyclo ./Middlewares/Lwip/src/api/err.d ./Middlewares/Lwip/src/api/err.o ./Middlewares/Lwip/src/api/err.su ./Middlewares/Lwip/src/api/if_api.cyclo ./Middlewares/Lwip/src/api/if_api.d ./Middlewares/Lwip/src/api/if_api.o ./Middlewares/Lwip/src/api/if_api.su ./Middlewares/Lwip/src/api/netbuf.cyclo ./Middlewares/Lwip/src/api/netbuf.d ./Middlewares/Lwip/src/api/netbuf.o ./Middlewares/Lwip/src/api/netbuf.su ./Middlewares/Lwip/src/api/netdb.cyclo ./Middlewares/Lwip/src/api/netdb.d ./Middlewares/Lwip/src/api/netdb.o ./Middlewares/Lwip/src/api/netdb.su ./Middlewares/Lwip/src/api/netifapi.cyclo ./Middlewares/Lwip/src/api/netifapi.d ./Middlewares/Lwip/src/api/netifapi.o ./Middlewares/Lwip/src/api/netifapi.su ./Middlewares/Lwip/src/api/sockets.cyclo ./Middlewares/Lwip/src/api/sockets.d ./Middlewares/Lwip/src/api/sockets.o ./Middlewares/Lwip/src/api/sockets.su ./Middlewares/Lwip/src/api/tcpip.cyclo ./Middlewares/Lwip/src/api/tcpip.d ./Middlewares/Lwip/src/api/tcpip.o ./Middlewares/Lwip/src/api/tcpip.su

.PHONY: clean-Middlewares-2f-Lwip-2f-src-2f-api

