################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/acd.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/autoip.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/dhcp.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/etharp.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/icmp.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/igmp.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4_addr.c \
C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4_frag.c 

OBJS += \
./Middlewares/Lwip/src/core/ipv4/acd.o \
./Middlewares/Lwip/src/core/ipv4/autoip.o \
./Middlewares/Lwip/src/core/ipv4/dhcp.o \
./Middlewares/Lwip/src/core/ipv4/etharp.o \
./Middlewares/Lwip/src/core/ipv4/icmp.o \
./Middlewares/Lwip/src/core/ipv4/igmp.o \
./Middlewares/Lwip/src/core/ipv4/ip4.o \
./Middlewares/Lwip/src/core/ipv4/ip4_addr.o \
./Middlewares/Lwip/src/core/ipv4/ip4_frag.o 

C_DEPS += \
./Middlewares/Lwip/src/core/ipv4/acd.d \
./Middlewares/Lwip/src/core/ipv4/autoip.d \
./Middlewares/Lwip/src/core/ipv4/dhcp.d \
./Middlewares/Lwip/src/core/ipv4/etharp.d \
./Middlewares/Lwip/src/core/ipv4/icmp.d \
./Middlewares/Lwip/src/core/ipv4/igmp.d \
./Middlewares/Lwip/src/core/ipv4/ip4.d \
./Middlewares/Lwip/src/core/ipv4/ip4_addr.d \
./Middlewares/Lwip/src/core/ipv4/ip4_frag.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/Lwip/src/core/ipv4/acd.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/acd.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/autoip.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/autoip.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/dhcp.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/dhcp.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/etharp.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/etharp.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/icmp.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/icmp.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/igmp.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/igmp.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/ip4.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/ip4_addr.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4_addr.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Lwip/src/core/ipv4/ip4_frag.o: C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/core/ipv4/ip4_frag.c Middlewares/Lwip/src/core/ipv4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -D_STM32CUBE_DISCOVERY_N657_ -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/config" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/include" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Appli/mtk3_bsp2/mtkernel/kernel/knlinc" -I"C:/Users/aayus/Documents/tron_26/master/mtk3bsp2_stm32n657/Middlewares/Lwip/src/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv4

clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv4:
	-$(RM) ./Middlewares/Lwip/src/core/ipv4/acd.cyclo ./Middlewares/Lwip/src/core/ipv4/acd.d ./Middlewares/Lwip/src/core/ipv4/acd.o ./Middlewares/Lwip/src/core/ipv4/acd.su ./Middlewares/Lwip/src/core/ipv4/autoip.cyclo ./Middlewares/Lwip/src/core/ipv4/autoip.d ./Middlewares/Lwip/src/core/ipv4/autoip.o ./Middlewares/Lwip/src/core/ipv4/autoip.su ./Middlewares/Lwip/src/core/ipv4/dhcp.cyclo ./Middlewares/Lwip/src/core/ipv4/dhcp.d ./Middlewares/Lwip/src/core/ipv4/dhcp.o ./Middlewares/Lwip/src/core/ipv4/dhcp.su ./Middlewares/Lwip/src/core/ipv4/etharp.cyclo ./Middlewares/Lwip/src/core/ipv4/etharp.d ./Middlewares/Lwip/src/core/ipv4/etharp.o ./Middlewares/Lwip/src/core/ipv4/etharp.su ./Middlewares/Lwip/src/core/ipv4/icmp.cyclo ./Middlewares/Lwip/src/core/ipv4/icmp.d ./Middlewares/Lwip/src/core/ipv4/icmp.o ./Middlewares/Lwip/src/core/ipv4/icmp.su ./Middlewares/Lwip/src/core/ipv4/igmp.cyclo ./Middlewares/Lwip/src/core/ipv4/igmp.d ./Middlewares/Lwip/src/core/ipv4/igmp.o ./Middlewares/Lwip/src/core/ipv4/igmp.su ./Middlewares/Lwip/src/core/ipv4/ip4.cyclo ./Middlewares/Lwip/src/core/ipv4/ip4.d ./Middlewares/Lwip/src/core/ipv4/ip4.o ./Middlewares/Lwip/src/core/ipv4/ip4.su ./Middlewares/Lwip/src/core/ipv4/ip4_addr.cyclo ./Middlewares/Lwip/src/core/ipv4/ip4_addr.d ./Middlewares/Lwip/src/core/ipv4/ip4_addr.o ./Middlewares/Lwip/src/core/ipv4/ip4_addr.su ./Middlewares/Lwip/src/core/ipv4/ip4_frag.cyclo ./Middlewares/Lwip/src/core/ipv4/ip4_frag.d ./Middlewares/Lwip/src/core/ipv4/ip4_frag.o ./Middlewares/Lwip/src/core/ipv4/ip4_frag.su

.PHONY: clean-Middlewares-2f-Lwip-2f-src-2f-core-2f-ipv4

